# Generated by Django 2.2.27 on 2022-02-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220218_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Icon',
            new_name='icon',
        ),
    ]
